[versions]
agp = "8.10.1"
coilCompose = "2.7.0"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
#hilt
hiltNavigationCompose = "1.2.0"
hiltAndroid = "2.51.1"
#navigation
navVersion = "2.9.0"
#ktor
ktorClientAndroid = "2.3.10"
ktorClientContentNegotiation = "2.3.10"
ktorClientCore = "2.3.10"
ktorClientLogging = "2.3.10"
ktorSerializationKotlinxJson = "2.3.10"
#room
roomVersion = "2.7.2"
#timber
timber = "5.0.1"
#lottie
lottieCompose = "6.5.0"
#font
uiTextGoogleFonts = "1.8.3"
#serialization
valSerialization = "2.1.20"
#ksp
ksp = "2.2.0-2.0.2"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
#hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
#navigation
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
#ktor
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-android = { module = "io.ktor:ktor-client-android",     version.ref = "ktorClientAndroid" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClientLogging" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorSerializationKotlinxJson" }
#room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
#timber
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
#lottie
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
#Icons
icons = "androidx.compose.material:material-icons-extended-android:1.7.8"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
#serialization
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref ="valSerialization" }
#ksp
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
#hilt
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref ="hiltAndroid" }


